--Secuencias

--Secuencia IDCLIENTE
CREATE   SEQUENCE sec_cliente
  INCREMENT BY 1 START WITH 1;

  --Secuencia PRODUCTO
CREATE   SEQUENCE sec_producto
  INCREMENT BY 1 START WITH 1;

  --Secuencia IDPEDIDO
CREATE  SEQUENCE sec_pedido
  INCREMENT BY 1 START WITH 1;

--Secuencia IDALBARAN
CREATE  SEQUENCE sec_albaran
  INCREMENT BY 1 START WITH 1;

--Secuencia IDFACTURA
CREATE SEQUENCE sec_factura
  INCREMENT BY 1 START WITH 1;

  --Secuencia LINEAPEDIDOS
CREATE SEQUENCE sec_lineaPedidos
  INCREMENT BY 1 START WITH 1;

--Secuencia IDOFERTA
CREATE SEQUENCE sec_oferta
  INCREMENT BY 1 START WITH 1;

  --Secuencia ID_DIRECCION
CREATE SEQUENCE sec_direccion
  INCREMENT BY 1 START WITH 1;
  
  --Secuencia ID_ALMACEN
CREATE SEQUENCE sec_almacen
  INCREMENT BY 1 START WITH 1;