--------------------------------------------------------
-- CREACION/ BORRADO DE TABLAS
--------------------------------------------------------
--------------------------------------------------------
--  BORRADO DE SECUENCIAS
--------------------------------------------------------
DROP SEQUENCE sec_municipio;
DROP SEQUENCE sec_carrito;
DROP SEQUENCE sec_provincia;
DROP SEQUENCE sec_cliente;
DROP SEQUENCE sec_producto;
--------------------------------------------------------
--  BORRADO DE TABLAS
--------------------------------------------------------
DROP TABLE CARRITOS; 
DROP TABLE CLIENTES; 
DROP TABLE PRODUCTOS;
DROP TABLE MUNICIPIOS;
DROP TABLE PROVINCIAS;

--------------------------------------------------------
--  CREACION DE TABLAS
--------------------------------------------------------

CREATE TABLE PROVINCIAS (
	NOMBRE VARCHAR2(25) NOT NULL,
	IDPROVINCIA INTEGER NOT NULL,
	PRIMARY KEY (IDPROVINCIA) );

CREATE TABLE MUNICIPIOS (
	NOMBRE VARCHAR2(200) NOT NULL,
	IDPROVINCIA INTEGER NOT NULL,	
	IDMUNICIPIO INTEGER NOT NULL,
	FOREIGN KEY (IDPROVINCIA) REFERENCES PROVINCIAS(IDPROVINCIA),
	PRIMARY KEY (IDMUNICIPIO) );

CREATE TABLE CLIENTES(
	IDCLIENTE INTEGER NOT NULL,
	DNI VARCHAR2(10) NOT NULL UNIQUE,
	NOMBRE_CLI VARCHAR(25) NOT NULL,
	APELLIDOS VARCHAR(75),
	DIRECCION VARCHAR2(75) NOT NULL,
	IDMUNICIPIO INTEGER NOT NULL,
	EMAIL VARCHAR(75) NOT NULL UNIQUE,
	PASS VARCHAR(75) NOT NULL,
	PRIMARY KEY(IDCLIENTE),
	FOREIGN KEY (IDMUNICIPIO) REFERENCES MUNICIPIOS(IDMUNICIPIO)	
);

CREATE TABLE CARRITOS (
	IDCLIENTE INTEGER NOT NULL,
	IDCARRITO INTEGER NOT NULL,
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES(IDCLIENTE),
	PRIMARY KEY (IDCARRITO) );

CREATE TABLE PRODUCTOS(
	CODIGO VARCHAR(50)NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL UNIQUE,
	DESCRIPCION VARCHAR(300),
	TIPOPRODUCTO VARCHAR(30) NOT NULL CHECK(TIPOPRODUCTO IN('equipoSoldadura','consumible','repuesto')),
	DISPONIBILIDAD VARCHAR(20) NOT NULL CHECK(DISPONIBILIDAD IN('Disponible','No disponible')),
	PRECIO FLOAT,
	URLDOCU VARCHAR(300),
	URLIMG VARCHAR(300),
	STOCK INT,
	PARTNUMBER VARCHAR(50) NOT NULL UNIQUE,
	MODELO VARCHAR(50),
	PRIMARY KEY(CODIGO)
);

--Secuencia IDCLIENTE
CREATE   SEQUENCE sec_cliente
  INCREMENT BY 1 START WITH 1;
  
--Secuencia IDCLIENTE
CREATE   SEQUENCE sec_carrito
	INCREMENT BY 1 START WITH 1;

  --Secuencia PRODUCTO
CREATE   SEQUENCE sec_producto
  INCREMENT BY 1 START WITH 1;
  CREATE SEQUENCE sec_provincia
START WITH 1 INCREMENT BY 1 NOMAXVALUE;

CREATE SEQUENCE sec_municipio
START WITH 1 INCREMENT BY 1 NOMAXVALUE;
--Triggers asociados a las secuencias
 
 CREATE OR REPLACE TRIGGER crea_ID_cliente
  BEFORE INSERT ON CLIENTES
  REFERENCING NEW AS NEW
  FOR EACH ROW
  BEGIN
  SELECT sec_cliente.NEXTVAL INTO :NEW.IDCLIENTE FROM DUAL;
  END;
/

 CREATE OR REPLACE TRIGGER crea_ID_carrito
  BEFORE INSERT ON CARRITOS
  REFERENCING NEW AS NEW
  FOR EACH ROW
  BEGIN
  SELECT sec_carrito.NEXTVAL INTO :NEW.IDCARRITO FROM DUAL;
  END;
/
CREATE OR REPLACE TRIGGER crea_ID_producto
  BEFORE INSERT ON PRODUCTOS
  REFERENCING NEW AS NEW
  FOR EACH ROW
  BEGIN
  SELECT sec_producto.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
  END;
/

CREATE OR REPLACE TRIGGER INSERTAR_MUNICIPIO
BEFORE INSERT ON MUNICIPIOS
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  SELECT sec_municipio.NEXTVAL INTO :NEW.IDMUNICIPIO FROM DUAL;
END;
/

create or replace PROCEDURE CREAR_CARRITO (
        id IN CARRITOS.IDCLIENTE%TYPE,
        precio IN CARRITOS.PRECIO%TYPE
    )
IS idcarrito CARRITOS.IDCARRITO%TYPE;
   BEGIN
        SELECT SEC_CARRITO.NEXTVAL INTO idcarrito FROM dual;
        INSERT INTO carritos (IDCLIENTE, PRECIO) 
        VALUES(id, precio);
END CREAR_CARRITO;
/
/